export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SOCIAL_LOGIN_INITIATED = 'SOCIAL_LOGIN_INITIATED';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const GET_PROFILE_PAYLOAD = 'GET_PROFILE_PAYLOAD';
export const GET_PROFILE_INITIATED = 'GET_PROFILE_INITIATED';

export const GET_ALL_ARTICLES_SUCCESS = 'GET_ALL_ARTICLES_SUCCESS';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_INITIATED = 'CREATE_ARTICLE_INITIATED';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
